version: '3.4'
services:
  mariadb:
    image: mariadb:10.4.11
    container_name: maria
    command:
      # docker run -it --rm mariadb:tag --verbose --help for liste med options
      - --character-set-server=utf8 #A UTF-8 encoding of the Unicode character set using one to four bytes per character.
      - --collation-server=utf8_general_ci
    environment:
      # Workaround https://github.com/docker-library/mariadb/issues/251, trolig fisket i 10.4.12
      - MYSQL_INITDB_SKIP_TZINFO=1
      # docker run -it --rm mariadb:tag --verbose --help for liste med options
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=brettspill
      - MYSQL_USER=brettspilladmin
      - MYSQL_PASSWORD=brettspilladmin
    ports:
      - "3306:3306"
    # logging:
      # driver: syslog
      # options:
        # tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
      - maria
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql  
     - ${PWD}/config:/etc/mysql/conf.d  

  
networks:
  maria:
    driver: bridge